#!/bin/sh
#SBATCH --job-name=
#SBATCH --nodes=                         # number of nodes
#SBATCH --mem=                         # memory pool for all cores
#SBATCH -t 168:00:00                       # time (HH:MM:SS)
#SBATCH --output=".txt"         # standard output
#SBATCH --error=".txt"          # standard error
#SBATCH --export=ALL
#SBATCH -p 

input=
        
# Author: Jennifer A Clark
nodes=${SLURM_JOB_NUM_NODES}
cores=${SLURM_CPUS_ON_NODE}
echo "Job ID: ${SLURM_JOB_ID}"
echo "Number of nodes:  ${SLURM_JOB_NUM_NODES}"
echo "CPUs per node:  ${SLURM_CPUS_ON_NODE}"
echo "Nodes: ${SLURM_NODELIST}"
echo "Queue: ${SLURM_JOB_PARTITION}"

# Modules for Gaussian 16
export OMP_NUM_THREADS=1
module purge
module load `/share/sw/gaussian/gaussian-assist/select-gaussian-version`

#module load pgi/16.5
export g16root=/home/hnr2/Linux_AVX2_Linda
. $g16root/g16/bsd/g16.profile

### Gaussian Settings ###########
#export GAUSS_PDEF=$SLURM_CPUS_ON_NODE
#echo "Gaussian PDEF ${GAUSS_PDEF}"

# Sets %mem in env variables
export GAUSS_MDEF="$(echo ${SLURM_MEM_PER_NODE}*0.7/1 | bc)MB" # Gaussian16 suggests using 70% of available memory per node
echo "Gaussian MDEF ${GAUSS_MDEF}, gives 70% of available RAM"

# Sets %CPU in env variables, specific to g16, replaces %nprocshared
Ncpus=$(echo ${SLURM_MEM_PER_NODE}*0.7/4000-1 | bc) # Give each core 4GB of RAM
if [ "${Ncpus}" -gt "$((${SLURM_CPUS_ON_NODE}-1))" ]; then # If we recommend more cores than exist, use the number on the node
    Ncpus=$((${SLURM_CPUS_ON_NODE}-1))
fi
export GAUSS_CDEF="0-${Ncpus}" # Gaussian documentation suggests specifying cores instead of NProcShared can speed up processing
echo "Gaussian CDEF ${GAUSS_CDEF}, gives each node 4GB or more of RAM"

# Set scratch directory 
export GAUSS_SCRDIR=/scratch/${USER}/${SLURM_JOB_ID}
mkdir -p ${GAUSS_SCRDIR}
echo "Gaussian SCRDIR ${GAUSS_SCRDIR}"


## Linda Settings ########
#export GAUSS_LFLAGS="--LindaOptions -s 20000000 -vv"
export GAUSS_LFLAGS="-vv"
export GAUSS_WDEF="`scontrol show hostnames | paste -s -d, -`"
export GAUSS_SDEF="ssh"
echo "Gaussian LFLAGS ${GAUSS_LFLAGS}"
echo "Gaussian WDEF ${GAUSS_WDEF}"
echo "Gaussian SDEF ${GAUSS_SDEF}"

#####
# Max scratch space added to routecard
maxdisk=`df /scratch | awk '/[0-9]%/{print $(NF-2)}'`
echo "This node has a maximum scratch space of ${maxdisk}"
cp ${input}_gas.com new_${input}_gas.com
sed -i "/^#n*/a # MaxDisk=${maxdisk}KB" new_${input}_gas.com  # Add the MaxDisk to the routecard in a new line

time g16 < new_${input}_gas.com > ${input}_gas.out &
wait

cp ${input}_PCM.com new_${input}_PCM.com
sed -i "/^#n*/a # MaxDisk=${maxdisk}KB" new_${input}_PCM.com  # Add the MaxDisk to the routecard in a new line

time g16 < new_${input}_PCM.com > ${input}_PCM.out &
wait

formchk ${input}_gas.chk &
wait
formchk ${input}_PCM.chk &
wait

rm -rf /scratch/${USER}/${SLURM_JOB_ID}
